apiVersion: apps/v1
kind: Deployment
metadata:
  name: akil-springbootapp
  labels:
    app: akil-springbootapp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: akil-springbootapp
  template:
    metadata:
      labels:
        app: akil-springbootapp
    spec:
      containers:
      - name: akil-springboot-container
        image: akil1991/akil-springbootapp:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: akil-springboot-service
spec:
  type: NodePort
  selector:
    app: akil-springbootapp
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30082
